### ISSUE TITLE
The experimental results differ from official reports

### ISSUE THREAD

**Issue by EWAN9709** [jayliu0313/Shape-Guided#4]
The experimental hardware configuration is as follows：
![image](https://github.com/jayliu0313/Shape-Guided/assets/82500501/3fdb7c7e-fb12-4f0d-b660-ce35f70f64e5)

The experimental results are as follows：
![image](https://github.com/jayliu0313/Shape-Guided/assets/82500501/b10e77e3-d80f-4608-8050-367555517222)

May I ask if our experimental results are normal? Looking forward to your reply

**Comment by jayliu0313** [comment]
I think that your RGB scores are not quite right because we use pretrained encoder to get the score, and it would not change the score. In addition, there's a difference in SDF scores compared to ours. May I ask if you trained the SDF model yourself?
If not, you should verify that "preprocessing.py" and "cut_patches.py" are executing correctly.
